name: OpenTimelineIO-Specification

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: sudo apt-get install graphviz
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/setup-node@v2
      with:
        node-version: '10'
    - run: |
        npm install
        npm run build
    - uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: |
          build/
          !build/otio.schema.json
    - uses: actions/upload-artifact@v2
      with:
        name: json-schmea
        path: build/otio.schema.json
